#!/bin/bash

echo "🚀 Script para subir CVs públicos a GitHub"
echo "=========================================="
echo ""

# Verificar que estamos en el directorio correcto
if [ ! -f "CV_Consultor_SAC_HTML.html" ]; then
    echo "❌ Error: No se encuentra CV_Consultor_SAC_HTML.html"
    echo "   Ejecuta este script desde el directorio cvs-publicos"
    exit 1
fi

echo "📊 Estado actual del repositorio local:"
echo "--------------------------------------"
git log --oneline -3
echo ""

echo "📁 Archivos listos para subir:"
echo "------------------------------"
ls -la *.html *.md
echo ""

echo "🔗 Enlaces que funcionarán después del push:"
echo "-------------------------------------------"
echo "1. CV HTML (raw):"
echo "   https://raw.githubusercontent.com/imanovabot/cvs-publicos/main/CV_Consultor_SAC_HTML.html"
echo ""
echo "2. Repositorio completo:"
echo "   https://github.com/imanovabot/cvs-publicos"
echo ""
echo "3. Guía de enlaces:"
echo "   https://raw.githubusercontent.com/imanovabot/cvs-publicos/main/CV_LINKS.md"
echo ""

echo "📋 PASOS PARA SUBIR A GITHUB:"
echo "============================="
echo ""
echo "1. 📝 CREAR REPOSITORIO EN GITHUB:"
echo "   ---------------------------------"
echo "   a. Ve a https://github.com/new"
echo "   b. Nombre: 'cvs-publicos'"
echo "   c. Descripción: 'CVs públicos para compartir con reclutadores'"
echo "   d. Público: ✅ MARCAR como público"
echo "   e. NO inicializar con README (ya tenemos uno)"
echo "   f. Click 'Create repository'"
echo ""
echo "2. 🔗 CONFIGURAR REMOTE:"
echo "   --------------------"
echo "   Ejecuta este comando (copia y pega):"
echo "   git remote add origin https://github.com/imanovabot/cvs-publicos.git"
echo ""
echo "3. 🚀 HACER PUSH:"
echo "   -------------"
echo "   Ejecuta este comando:"
echo "   git push -u origin master"
echo ""
echo "   (Si GitHub usa 'main' en lugar de 'master'):"
echo "   git branch -M main && git push -u origin main"
echo ""
echo "4. ✅ VERIFICAR:"
echo "   ------------"
echo "   Visita: https://github.com/imanovabot/cvs-publicos"
echo "   Deberías ver los 3 archivos"
echo ""

echo "💡 CONSEJOS:"
echo "==========="
echo ""
echo "• Si el token ha expirado, necesitarás:"
echo "  1. Generar nuevo token en GitHub: Settings → Developer settings → Personal access tokens"
echo "  2. Seleccionar scopes: 'repo' (acceso completo a repositorios)"
echo "  3. Usar: git remote set-url origin https://TU_TOKEN@github.com/imanovabot/cvs-publicos.git"
echo ""
echo "• Para actualizar en el futuro:"
echo "  git add ."
echo "  git commit -m 'Actualización CV'"
echo "  git push"
echo ""
echo "• Los enlaces raw.githubusercontent.com funcionan inmediatamente"
echo "  después del push (no hay delay como con repositorios privados→públicos)"
echo ""

echo "🎯 RESUMEN:"
echo "=========="
echo "✅ Repositorio local creado: /tmp/cvs-publicos/"
echo "✅ Archivos listos: CV HTML + guía de enlaces"
echo "⏳ Falta: Crear repositorio en GitHub y hacer push"
echo ""
echo "¿Necesitas ayuda con algún paso específico?"